spring.application.name=url-shortner
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=******
spring.datasource.password=******
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# App Configuration
app.url.shortener.id-counter-key=url_shortener_id_counter
app.url.shortener.cache-ttl-hours=24

